refactor: use fc-go-sdk vsock module
firecracker-microvm/firecracker-containerd pull request #585
Opened 2022-03-02 16:45 UTC by austinvazquez

*Issue #, if available:*

*Description of changes:*
Use the vsock module that was refactored into the firecracker-go-sdk.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-02 17:29 UTC, kzys commented
The main branch has some fixes regarding our test stability. Can you rebase your branch?

2022-03-02 18:37 UTC, austinvazquez commented
> The main branch has some fixes regarding our test stability. Can you rebase your branch?

Rebasing off main instead of containerd-1.6 branch.

2022-03-02 19:34 UTC, kzys commented
You need to remove https://github.com/firecracker-microvm/firecracker-containerd/blob/main/internal/vm/vsock_test.go.

2022-03-02 19:38 UTC, kzys requested changes

2022-03-02 19:38 UTC, kzys commented on internal/vm/vsock.go
> +			conn, err := vsock.Dial(timeoutCtx, logger, udsPath, port)
Can you upgrade the SDK to the latest version and use DialContext here instead? It is needed to have https://github.com/firecracker-microvm/firecracker-go-sdk/pull/390.

2022-03-04 05:00 UTC, Kern-- approved these changes

2022-03-07 21:39 UTC, merged