Add remote snapshotter rootfs (stargz)
firecracker-microvm/firecracker-containerd pull request #613
Opened 2022-04-27 18:48 UTC by Kern--

This change adds tooling to build a firecracker rootfs with
stargz as a remote snapshotter. This rootfs can be combined
with the demux-snapshotter to launch stargz containers inside
the firecracker vm.

Signed-off-by: Kern Walster <walster@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-27 20:19 UTC, kzys requested changes

2022-04-27 20:19 UTC, kzys commented on docker-credential-mmds/main.go
> +		fmt.Fprintf(os.Stderr, "containerd: %s\n", err)
containerd -> probably the name of this binary?

2022-04-27 20:19 UTC, kzys commented on tools/image-builder/files_debootstrap/sbin/overlay-init
> +fi
How about doing that in systemd instead of this init?

2022-04-27 20:19 UTC, kzys commented on docker-credential-mmds/mmds/client.go
> +		return []byte{}, errors.New(fmt.Sprintf("Unexpected http response: %d - (err %w) %s", status, err, string(body)))
You can use fmt.Errorf instead

2022-05-02 22:28 UTC, austinvazquez commented on docker-credential-mmds/mmds/helper.go
> +// Helper implements the docker crednetial helper interface
credential*

2022-05-02 23:07 UTC, austinvazquez approved these changes
Minor nits, but this looks good to me.

2022-05-02 23:07 UTC, austinvazquez commented on examples/cmd/remote-snapshotter/Makefile
> +SOURCES:=$(shell find . -name '*.go')
Unused.

2022-05-03 18:52 UTC, kzys commented
@Kern-- I have resolved my comments you've addressed. Can you check open ones?

2022-05-03 19:31 UTC, Kern-- commented on docker-credential-mmds/mmds/helper.go
> +}
I added a brief explanation in the `Helper` struct doc string. I created https://github.com/firecracker-microvm/firecracker-containerd/issues/618 to track the documentation we need around remote snapshotters in general.

2022-05-03 22:03 UTC, kzys approved these changes

2022-05-03 22:04 UTC, kzys commented
The change looks good. Please rebase that against main to fix the lint issue.

2022-05-04 20:58 UTC, merged